version: "3.1"
services:
    db:
        image: mysql
        container_name: db-mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: asir2_db
            MYSQL_ROOT_PASSWORD: 123456
#            MYSQL_USER: asir2iaw
#            MYSQL_PASSWORD: 123456
        volumes:
            - ./db-mysql-data:/var/lib/mysql
            
    phpapp:
        build: .
        container_name: phpapp
        restart: always
        volumes:
            - ./www:/var/www/html
        ports:
            - 80:80
        depends_on:
            - db

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            - PMA_ARBITRARY=1
        ports:
            - "8081:80"
        depends_on:
            - db
